name: CI

on: [push]

env:
  extensions:  mysqli, mbstring, intl, iconv, libxml, dom, json, simplexml, zlib, fileinfo
  defaultPHPVersion: '8.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ env.defaultPHPVersion }}
        extensions: ${{ env.extensions }}
        ini-values: memory_limit=2G, display_errors=On, error_reporting=-1
        tools: composer-require-checker:2.1.0

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: webroot/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
  phpcs:
    runs-on: ubuntu-latest
    name: PHP coding standard check
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ env.defaultPHPVersion }}
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=2G, display_errors=On, error_reporting=-1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: webroot/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run phpcs
        run: make cs
  phpstan:
    runs-on: ubuntu-latest
    name: PHP static analysis
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ env.defaultPHPVersion }}
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=2G, display_errors=On, error_reporting=-1

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: webroot/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run phpstan
        run: make stan